coverage:
  status:
    project:
      default:
        # Fail the status if coverage drops by >= 5%
        threshold: 5
    patch:
      default:
        threshold: 5

comment:
  layout: diff
  require_changes: yes